### ISSUE TITLE
Clone objects before they are returned from cache

### ISSUE THREAD

**Issue by evansolomon** [tollmanz/wordpress-pecl-memcached-object-cache#22]
When PHP returns an object, it does so by reference, which means that the returned value has the capability to change the "original" value.  This tends not to matter, but in the case of object caching it can cause big (and confusing) problems.  If an object (i.e. `is_object()`, not just a generic name for data) is returned from cache, then changed, the change affects the data in the cache.  The most common way this manifests itself in WordPress is through filters.  Here's an example.

``` php
function es_runaway_filter( $theme ) {
    $theme->price = $theme->price * 2;
    return $theme;
}
add_filter( 'get_premium_theme', 'es_runaway_filter' );

function get_premium_theme( $id ) {
    // Let's assume this object is always in cache
    return apply_filters( 'get_premium_theme', wp_cache_get( $id, 'themes' ) );
}

echo get_premium_theme( 123 )->price; // Let's say this prints 100
echo get_premium_theme( 123 )->price; // This prints 200
echo get_premium_theme( 123 )->price; // This prints 400
```

As you can see, each successive call gets the data that's already been altered by all of the previous calls.

The solution to this is to check if a value is an object (again, `is_object()` style) before returning it from cache (local and remote).  If it is, `clone` it before returning it for happy filtering.

**Comment by tollmanz** [comment]
Interestingly, this bit be again. I needed to clone objects before _setting_ to cache. In particular, this is an issue if you add an object to the _internal cache_ and request it again in the same run time. Your patch helped with persistent requests, but I found the within run time requests still had this problem.
