### ISSUE TITLE
Slows down site

### ISSUE THREAD

**Issue by Coopeh** [tollmanz/wordpress-pecl-memcached-object-cache#24]
Any reason why this would add 6-10 seconds of page generation time? I'm assuming I have a configuration problem somewhere. I have both memcache and memcached pecl extensions installed, wp-config is configured as you specified and my memcached config is below:

-d
logfile /var/log/memcached.log
-m 512
-p 11211
-u memcache
-l 127.0.0.1
-c 4096
-k
-r
-t 8
-b 8196

Cheers,
Ed

**Comment by tollmanz** [comment]
Hi @Coopeh!

I totally missed this report. Sorry about that! I have no reason to think the plugin would cause a 6-10 second slow down :frowning: 

I would probably test memcached with a simple PHP script just to rule that out as the problem:

``` php
$m = new Memcached();
$m->addServer( '127.0.0.1', 11211 );

$m->set( 'foo', 100 );
var_dump( $m->get( 'foo' ) );
```

That will quickly tell you if it is setup correctly.

**Comment by Coopeh** [comment]
Hi, no problem.

Yeah, that test script works no problem. When I add your object-cache.php back in though it ups page generation time from 1 seconds to 8 at the moment. Is there anything else I can test?

Cheers,
Ed

**Comment by Coopeh** [comment]
Right, some more testing. It appears that it only effects Super Admins on a Multisite install. All other users are sped up considerably, so not sure what that could be. I'll have a play about with some plugins and see if anything changes.

Ed

**Comment by Coopeh** [comment]
Removed my user and created a new one has fixed it, not sure what it was loading that caused it to slow down so much. Possibly due to having too many blogs attached to me?

Ed

**Comment by tollmanz** [comment]
@Coopeh thanks for the follow-up information! This is something I will need to examine further. I am going to open this ticket back up for now so I remember to investigate. This _may_ be related to #23.

**Comment by Coopeh** [comment]
It's back to being slow again unfortunately. Seems to be as I add new blogs over time.

Ed

**Comment by tollmanz** [comment]
@Coopeh I have a few questions for you:
1. Any reason why you have the memory set to 512M? 
2. Are you running memcached on the same server as your db server and your web nodes?
3. How many memcached servers are you running?
4. How many sites are you running?

**Comment by Coopeh** [comment]
Hi,

1) It's currently at 768mb of ram and nearly all used, it's for a large multisite install. 
2) Yeah, all on the same server at the moment.
3) 3 instances, but only one for this multisite install.
4) it's running about 10,000 blogs currently. 

Cheers,

Ed

**Comment by tollmanz** [comment]
Hi @Coopeh! Thanks for the information. 

My first reaction is WHOA!!! 10,000 blogs and only a single memcached server is likely a major problem. I'm guessing that you are experiencing two issues: 
1. You do not have enough memory dedicated to memcached. I would think that you'd want at least 2 GB of memory total.
2. You should have probably at least 2 memcached boxes. I would try to give each 2GB of memory.

It sounds like your memory is filling up, which will cause memcached to kick a bunch of stuff out of memory. The net result is that you need to regenerate that data which will put a lot more load on your web nodes and database server.

Memcached can do a lot of things, but I think you are likely just exhausting your resources and need to consider bumping your hardware up on this set up.

**Comment by Coopeh** [comment]
Hi,

We aren't actually running out of resources on the server. I've upped the limit to 1GB over the last few days and it's never hit anywhere near it's maximum. Looking at phpMemcachedAdmin, it usually uses up to about 768mb of RAM and then seems to stop. Not sure if that is due to flushing occurring, also not sure what causes the flushes to happen, plugin/theme upgrades? The actual connection rate to memcached it quite low, they're used by school children so they're not continuously in use.

As I mentioned before, as far as I know this is only affects super admins with lots of blogs attached to them. If you're a normal user or admin then it loads extremely quickly, so it's working effectively for them. 

Cheers,
Ed

**Comment by tollmanz** [comment]
Have you looked at your resource utilization when a superadmin is doing superadminy things? My hunch is that superadmins are causing significant MySQL queries, which is slowing down their experience. If this is the case, there could be a few things happening:
1. My memcached library is just not working with superadmins. As indicated above, this could be related to #23.
2. You may have some custom code that is spinning out of control for super admins. I would look at the MySQL slow query log, or even the log of queries via the Debug Bar Extender plugin for when a super admin is logged in.

**Comment by Coopeh** [comment]
Hi, sorry for the delay. Here are my findings:

Visiting Network > Settings page:

Brand new Super Admin:
  Ram usage: ~20mb
  Flow profile: https://gist.github.com/Coopeh/5698010

Old Super Admin with 3 attached blogs, more in past, but removed:
  Ram usage: ~80mb
  Flow profile: https://gist.github.com/Coopeh/5698020

It appears that the adminmenu action is causing a delay as it switches through the blogs. So I assume that means it is the #23 issue.

Cheers,
Ed

**Comment by tollmanz** [comment]
@Coopeh Hmmm...looks like I let this grow way stale. I'd like to look into it some more. Are you still attempting to use the drop-in? If so, I've since resolved #23, which I hope improves the experience for you. I'd be really interested to see if the update fixes this issue.

**Comment by Coopeh** [comment]
Hi @tollmanz. I'm using it on another multisite installation, started on WP3.7, and it doesn't really slow down on this one. The previous installation was for another company I no longer work for. I'll pass on for them to test it and get back to me.

**Comment by Coopeh** [comment]
I've just tested this on my install, it's made it much, much faster, so that's a bonus for me. Thanks!

**Comment by tollmanz** [comment]
Good to know @Coopeh! I'll keep this ticket open for a while longer. It sounds like things are fixed, but I'll wait a little bit to hear back about the original install.

**Comment by tollmanz** [comment]
Closing this due to no feedback. I think this is a problem that has been resolved.
