### ISSUE TITLE
Composer support

### ISSUE THREAD

**Issue by einkoro** [tollmanz/wordpress-pecl-memcached-object-cache#46]
Any thoughts on adding composer support? I think it would go well with publishing on the WP plugin repo (https://github.com/tollmanz/wordpress-pecl-memcached-object-cache/pull/26) as it would then be included on http://wpackagist.org/

http://roots.io/wordpress-plugins-with-composer/

**Comment by tollmanz** [comment]
Great idea...I'd love to do it!

**Comment by tollmanz** [comment]
Handled in #51
