### ISSUE TITLE
License

### ISSUE THREAD

**Issue by bonny** [tollmanz/wordpress-pecl-memcached-object-cache#59]
Hey hey, what's the license of this wonderful thing? I want to use it in another plugin I'm making, is that okelidokely?

**Comment by bonny** [comment]
Ok, I just assume it's ok for now, and my plugin using code from this repo is now online here:
https://github.com/bonny/memcachy

**Comment by tollmanz** [comment]
That's fine. Just be sure to continually update your plugin based on updates in mine. I don't officially have a license at this point, but it will likely be GPLv2 or MIT. I need to do a few things before I can make that official.
