### ISSUE TITLE
Does this correctly handle objects with expiration times more than 30 days in the future?

### ISSUE THREAD

**Issue by jeffwidman** [tollmanz/wordpress-pecl-memcached-object-cache#60]
See here: https://remaintenance.io/blog/2015/02/fixing-woocommerce-memcached-performance/

Basically when expiration is set more than 30 days in the future, other memcache object cache implementations have problems. 

Does this implementation handle that scenario correctly?

**Comment by tollmanz** [comment]
Yup. We dealt with this about a year ago: https://github.com/tollmanz/wordpress-pecl-memcached-object-cache/pull/35. I find it a little silly to explicitly set an object to cache for 30+ days, but we have handled that issue.

**Comment by jeffwidman** [comment]
Thanks!
