### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by tollmanz** [tollmanz/wordpress-pecl-memcached-object-cache#63]
I failed to specify a license when this was initially released. Since then, I have accepted contributions from others. Following [VVV's lead](https://github.com/Varying-Vagrant-Vagrants/VVV/issues/346), I think it is important that current contributors have a say in the licensing.

I think we should settle on MIT or GPLv2 and I personally lean toward MIT, but am up for any thoughts folks have.

Can the following individuals please let me know your preference:
- [x] @Giuseppe-Mazzapica 
- [x] @swalkinshaw 
- [x] @aaronjorbin 
- [x] @JustinSainton 
- [x] @cmmarslender 
- [x] @webaware 
- [x] @Ramoonus 

Thanks, everyone!

**Comment by swalkinshaw** [comment]
MIT

**Comment by Ramoonus** [comment]
Can I not vote
I have no in depth knowledge of both so I cannot decide

**Comment by tollmanz** [comment]
> Can I not vote
> I have no in depth knowledge of both so I cannot decide

That's fine. Are you ok with whatever decision we make then?

**Comment by JustinSainton** [comment]
Happy with MIT.  Worth noting for others, MIT is GPL2 compatible

**Comment by cmmarslender** [comment]
MIT is also fine with me.

**Comment by gmazzap** [comment]
MIT

**Comment by aaronjorbin** [comment]
How about Affero General Public License?

I'm actually fine with whatever @tollmanz wants.  He's the lead of the
project and I trust him. I'll vote for whatever he votes for.

http://aaron.jorb.in
twitter: twitter.com/aaronjorbin

**Comment by tollmanz** [comment]
> Affero General Public License

Never heard of it, but that is really interesting. I generally like the idea behind it, but have no interest in even trying to enforce that.

I think you are voting for MIT :smile:

**Comment by webaware** [comment]
[OK, I'm with you fellas](https://youtu.be/9xJkUyotSc4)... MIT.

**Comment by tollmanz** [comment]
Awesome! Thanks all. MIT it is! PR forthcoming.
