### ISSUE TITLE
Debug Bar looks for a `stats` method on the WP Object Cache class

### ISSUE THREAD

**Issue by joelataylor** [tollmanz/wordpress-pecl-memcached-object-cache#68]
But it doesn't seem this class has that method defined. Any suggestions?

`$this->set_visible( is_object( $wp_object_cache ) && method_exists( $wp_object_cache, 'stats' ) );`

**Comment by tollmanz** [comment]
@joelataylor Some of the other WordPress object caches have a `stats` method that will return information about the number of sets and gets in the current request. I never found this to be of much use and didn't include such a feature in this object cache. Debug Bar's implementation of this is half baked and the UI is so unusable. I'm not at all wanting to make any changes to compliment that.

If you are interested in seeing memcached stats, I recommend [phpmemcacheadmin](https://code.google.com/p/phpmemcacheadmin/). It's a simple monitoring tool that will show you what your memcached server has been up to.

Additionally, this object cache has a `wp_cache_get_stats()` function that will reveal a lot of information if you want to work that into a UI. Moreover, if you use the code on the develop branch, there is a wonderful `wp mem stats` WP CLI command that will give you beautifully formatted stat information. Hopefully one of these options will satisfy your needs.
