### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by franz-josef-kaiser** [tollmanz/wordpress-pecl-memcached-object-cache#70]
By now there are [no tags](https://github.com/tollmanz/wordpress-pecl-memcached-object-cache/releases). This makes it hard (or: impossible) to use anything aside from _fake_ releases (branch aliasing) via Composer. This also makes it impossible to request this package without Composer using Git, cloning everything and then checking out the specific tag. This should get fixed.

**Comment by franz-josef-kaiser** [comment]
Please tag as following:

```
git tag -a 1.0.0 d4d0840 -m "First fully functional version"
git tag -a 2.0.0 8a6f581 -m "Support Composer"
```

…where the `-m`/message can be set to your likings. :)

**Comment by franz-josef-kaiser** [comment]
Hey @tollmanz 
Any progress on that? That one is really easy and above isn't just a random sample, but I searched up the _real_ commits where the tags belong. Hope you can move that one in. Thanks a bunch!

**ProTip:** When you are done, you can create [beautiful releases](https://github.com/tollmanz/wordpress-pecl-memcached-object-cache/releases) that you can reference to.

**Comment by tollmanz** [comment]
Totally missed this issue.

I'm happy to tag 1.0.0, but 2.0.0 is not released yet. I'm still working out how to release this on .org for the official 2.0.0 release...trying to find a way for it to live along side the other memcached library with the least amount of confusion.

How about if I tagged a 2.0.0-alpha?

**Comment by franz-josef-kaiser** [comment]
> How about if I tagged a `2.0.0-alpha`?

You can do that. Composer can live with it pretty happy. Also you can tick the "this is a pre-release"-checkbox on bottom when you draft a pre-release here in GitHub [Releases](../../releases).

**Comment by franz-josef-kaiser** [comment]
@tollmanz ping :)

**Comment by tollmanz** [comment]
We now have `1.0.0` and `2.0.0-alpha`. I'm horrible for taking so long to do this. Thanks for your patience.

**Comment by franz-josef-kaiser** [comment]
Thanks a bunch, Zack!

(Now: [Releases](https://github.com/tollmanz/wordpress-pecl-memcached-object-cache/releases) because they look nice)
