### ISSUE TITLE
Fatal error:  Class 'Memcached' not found in php shell code on line 1

### ISSUE THREAD

**Issue by BrunoSette** [tollmanz/wordpress-pecl-memcached-object-cache#71]
i see that message when typing: $m = new Memcached();

Any Help?

**Comment by shmuel-krakower** [comment]
Hi @BrunoSette  - you get this error because the Memcached php extension is missing from your installation. Run phpinfo() and look for 'Memcached' (you probably won't find it). This plugin was created to work with Memcached and not Memcache.

**Comment by tollmanz** [comment]
Sorry for missing this @BrunoSette. Thanks for helping @shmuel-krakower!

@shmuel-krakower is 100% correct. You need to install [PECL Memcached](http://serverfault.com/questions/238110/how-to-install-pecl-memcached). It is really unfortunate that there is a "memcache" and "memcached" PECL extension :/ It leads to a lot of confusion.
